# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autokitteh < Formula
  desc "Durable workflow automation in just a few lines of code"
  homepage "https://autokitteh.com/"
  version "0.19.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/autokitteh/autokitteh/releases/download/v0.19.3/autokitteh_darwin_x86_64.tar.gz"
      sha256 "2bf757008f5e25e3db354e7e5444bac5bfa3d3a333bc4b43bbecde49abad8959"

      def install
        bin.install "ak"
        generate_completions_from_executable(bin/"ak", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/autokitteh/autokitteh/releases/download/v0.19.3/autokitteh_darwin_arm64.tar.gz"
      sha256 "68551fbfb599e4009e7903fee04087a2c3a0dc698a768abda181364d05df2583"

      def install
        bin.install "ak"
        generate_completions_from_executable(bin/"ak", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/autokitteh/autokitteh/releases/download/v0.19.3/autokitteh_linux_x86_64.tar.gz"
      sha256 "d46c52d656931f8b04942da362cdc0d0b783cd63e3ef2ae50c491d7a8d9ff297"
      def install
        bin.install "ak"
        generate_completions_from_executable(bin/"ak", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/autokitteh/autokitteh/releases/download/v0.19.3/autokitteh_linux_arm64.tar.gz"
      sha256 "f17898be53a93d976ac3abb3abd695ad5de68965d0a458e300c3130f36b8bef8"
      def install
        bin.install "ak"
        generate_completions_from_executable(bin/"ak", "completion")
      end
    end
  end

  test do
    system "#{bin}/ak version"
  end
end
