# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autokitteh < Formula
  desc "Durable workflow automation in just a few lines of code"
  homepage "https://autokitteh.com/"
  version "0.19.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/autokitteh/autokitteh/releases/download/v0.19.2/autokitteh_darwin_x86_64.tar.gz"
      sha256 "e2688da60eb393568443190ace5fd2125ed8a3cb93585e426c9d663ca6cbac36"

      def install
        bin.install "ak"
        generate_completions_from_executable(bin/"ak", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/autokitteh/autokitteh/releases/download/v0.19.2/autokitteh_darwin_arm64.tar.gz"
      sha256 "e46a3bafff5acf0ac313fcbd7199bc9aff6d39995699277044976fb884342bb2"

      def install
        bin.install "ak"
        generate_completions_from_executable(bin/"ak", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/autokitteh/autokitteh/releases/download/v0.19.2/autokitteh_linux_x86_64.tar.gz"
      sha256 "6cbca0c0a8eb4cb48c909daf3e1c230fa4598d14c6a158dab2c527f7f106825b"
      def install
        bin.install "ak"
        generate_completions_from_executable(bin/"ak", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/autokitteh/autokitteh/releases/download/v0.19.2/autokitteh_linux_arm64.tar.gz"
      sha256 "b2c95f3f4f6d847fef5f0fa76fbcc30111eec45e0f5f1c9a988483a13d25f2d5"
      def install
        bin.install "ak"
        generate_completions_from_executable(bin/"ak", "completion")
      end
    end
  end

  test do
    system "#{bin}/ak version"
  end
end
