# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Autokitteh < Formula
  desc "Durable workflow automation in just a few lines of code"
  homepage "https://autokitteh.com/"
  version "0.21.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/autokitteh/autokitteh/releases/download/v0.21.3/autokitteh_darwin_x86_64.tar.gz"
      sha256 "fdc4d7eb8ac9ac149a15da8fc4c8c12fc659fa712a38e327b756709ce360a198"

      def install
        bin.install "ak"
        generate_completions_from_executable(bin/"ak", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/autokitteh/autokitteh/releases/download/v0.21.3/autokitteh_darwin_arm64.tar.gz"
      sha256 "2f86e055f67454cfbd37f68c41ba90ed2c19dc0ecd6c2814bb7c1698de4c5cc5"

      def install
        bin.install "ak"
        generate_completions_from_executable(bin/"ak", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/autokitteh/autokitteh/releases/download/v0.21.3/autokitteh_linux_x86_64.tar.gz"
      sha256 "d0d257d6472f5b437c54853ad839199b0b0752a10dfd72d4a9126e6a1672ee86"
      def install
        bin.install "ak"
        generate_completions_from_executable(bin/"ak", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/autokitteh/autokitteh/releases/download/v0.21.3/autokitteh_linux_arm64.tar.gz"
      sha256 "0cd5a42b3a647b9cb5ffd0d045508366b9ec15897c239fdef5b954bd6e9df894"
      def install
        bin.install "ak"
        generate_completions_from_executable(bin/"ak", "completion")
      end
    end
  end

  test do
    system "#{bin}/ak version"
  end
end
